syj67507/github-pr-chrome-extension

src/popup/components/PRDisplay/RepoSection/RepoTitle.jsx
src/popup/components/PRDisplay/RepoSection/index.jsx
src/popup/components/PRDisplay/index.jsx

In this PR, the extension initially hides the PR's from view underneath the repo's title. This was added to handle situations where there may be so many PR's open for a repo section that makes it harder to navigate to other repo's PR's.
- Added the Accordion component for use in the RepoSection component
- Updated layout of RepoTitle
- Moved opening tab to repo's homepage to just the Box surrounding the title

Feature - Collapsible Pull Requests

---

src/background/background.js

In this PR, the issue where an error would be thrown by the background script and failing to set the badge to how many open PR's there were has been fixed. The issue seem to come from an earlier update to change the use of `module.exports` to `export default`.
- Using `import` syntax instead of `require` syntax

Bug - Background Script Not Setting Badge Fixed

---

package-lock.json
package.json
src/background/background.js
src/data/extension.js

In this PR, all extension API related code has been replaced with using the `webextension-polyfills` package. This allows for the extension to be functional on other browsers other than Chrome. However, this PR does not properly build the project as a Firefox add-on yet.
- Installed `webextension-polyfills`
- Replaced all `chrome.` calls with `Browser.` from the new package

Refactor - Using WebExtension-Polyfills

---

src/data/extension.js
src/data/index.js
src/popup/components/Options/components/Add/index.jsx
src/popup/components/Options/components/Saved/SavedRepo/index.jsx

In this PR, each repository can now be configured with more than one JIRA tag. Each additional tag can be defined by placing a comma in between each JIRA tag.
Example
```
One tag: "FOO"
Two tags: "FOO,BAR"
```
- `jiraTag` property name changed to `jiraTags`
- `TextField` component prompts for adding a repository have better descriptions
- Refactored parsing of JIRA tickets in pull request data for multiple tags
- Viewing saved repos updated to parse multiple tags

Feature - Multiple JIRA Tags

---

src/popup/components/PRDisplay/RepoSection/RepoTitle.jsx

In this PR, the icon for expanding has been switched out for a new tab icon indicating that clicking the button will now open the repo in a new tab. Clicking anywhere else on the repo's title will expand the dropdown allowing for view of the open PR's. This came about as making it easier to stay in the extension and not be brought to another screen accidentally.
- Icon's changed
- Clicking title expands, clicking new tab icon brings up the repository in a new tab
- Tooltip used to describe how many PR's are open for a given repository

Refactor - Switch Open Tab and Expand Behavior

---

.eslintrc.json
package-lock.json
package.json
src/background/background.ts
webpack/chrome/webpack.chrome.js
webpack/firefox/webpack.firefox.js

In this PR, the `src/background` files have been converted into TypeScript. This is part of the refactor to convert all source code into TypeScript.
- `background.js` converted to `background.ts`
- ESLint ignore overrides used for allowing asynchronous methods in the background script handlers
- webpack configurations updated to allow for the background entry point to reference the typescript file
- ESLint config updated to ignore webpack configurations

Refactor - Convert src/background to TypeScript

---

package-lock.json
src/data/extension.ts

In this PR, the functionality to set and fetch from storage has been changed from sync to local. This is because of an issue where my work email would automatically be in a "Paused" state and essentially sign out. This would cause the sync storage to clear and I would have to re-input all the information again.
This is a temporary fix and will be refactored to allow the user to select the option if they want to sync it across browsers or store it locally.
- ran `npm audit fix` to update packages
- Changed `.sync` to `.local` for browser storage

Bugfix: Use Local Storage instead of Sync Storage

---

src/background/background.ts
src/data/extension.ts
src/popup/components/Settings/AccessTokenSetting.tsx
src/popup/components/Settings/ClearStorageSetting.tsx
src/popup/components/Settings/index.tsx
src/popup/popup.tsx

In this PR, the change to use local storage for browser extensions / add-ons have been reverted back to using sync storage. An additional setting has been added to clear the user's storage should there be invalid data. The extension / add-on will no longer clear the storage upon installation.
The main reason for this change was to further investigate why the extension would have no data. The issue came from the extension effectively being reinstalled. Not sure why this was the behavior for extension in these cases but this should prevent the extension from being cleared of data.
- Refactored Permissions to be renamed and separated out into different Settings Components
- `extension.ts` updated to use sync storage in all data manipulation functions
- `onInstalled` handler no longer calls …

Refactor: Sync Storage

---

src/background/background.ts
src/data/extension.ts
src/popup/components/Settings/ClearStorageSetting.tsx

In this PR, an issue where storage values could not be set has been resolved. The issue came from the fact that any `setStorage()` calls would error because the storage API didn't have an object initialized in place of where the values would be set.
Previously the `clearStorage()` (now renamed to `resetStorage()` was removed from the `onInstall` event of the background script to prevent pre-existing data from being cleared. This would mean that there was no object initialized for storage that caused the `setStorage()` calls to fail. Now this event will check to see if there is any pre-existing data, and call a reset to initialize the storage object if there isn't any.
- renamed `clearStorage()` to `resetStorage()`
- `onInstall` event calls `resetStorage()` if no pre-existing data is …

Bugfix: Resets Storage on Install

---

src/data/extension.ts
src/data/index.ts
src/popup/components/PRDisplay/Filters/Filters.tsx
src/popup/components/PRDisplay/RepoSection/NoPullRequest.tsx
src/popup/components/PRDisplay/RepoSection/PullRequest/GitHubIconButton.tsx
src/popup/components/PRDisplay/RepoSection/PullRequest/JiraIconButton.tsx
src/popup/components/PRDisplay/RepoSection/PullRequest/index.tsx
src/popup/components/PRDisplay/RepoSection/RepoHeader.tsx
src/popup/components/PRDisplay/RepoSection/index.tsx
src/popup/components/PRDisplay/index.tsx
src/popup/popup.tsx

In this PR, more filters have been added as check boxes to better find the pull requests that a user would be looking for. Due to the way the current code was set up, prop drilling became a bit too cumbersome for my taste and I implemented a refactor to make it easier to filter out the pull requests that were to be displayed.
- Refactored the `<RepoSection />` component to now define the `<PullRequest />` components as direct children rather than passing in the `repos` data through the props
- This helps to define the filters at the top of the tree and filter out the data in the same location without too many layers of prop drilling
- `<Filters /> component created to define one spot where all filters are handled
- `GitHubClient` has a few interfaces renamed and added additional data for …

Feature: Adding Draft and Mine Checkbox Filters

---

src/popup/components/Settings/AccessTokenSetting.tsx
src/popup/components/Settings/ClearStorageSetting.tsx
src/popup/components/Settings/ResetStorageSetting.tsx
src/popup/components/Settings/index.tsx

In this PR, alerts now appear at the top of the page when manipulating the settings. When a user attempts to save their token or reset their storage, there will be either a success or error alert depending on whether or not the action was successful.
- Added Alert component logic to be displayed at the base of the settings component
- Inner settings component now takes in props for the alert state so that it can properly send information on what alert to show
<details><summary>Click to open / close</summary>
<p>
</p>
</details>

Feature: Add Visual Feedback on Settings Page

---

src/popup/components/Buttons/ClearButton.tsx
src/popup/components/Buttons/SaveButton.tsx
src/popup/components/PRDisplay/Filters/Filters.tsx
src/popup/components/PRDisplay/RepoSection/PullRequest/index.tsx
src/popup/components/PRDisplay/index.tsx
src/popup/components/RepoOptions/components/Add/index.tsx
src/popup/components/Settings/AccessTokenSetting.tsx
src/popup/components/Settings/ResetStorageSetting.tsx
src/popup/components/Settings/index.tsx

In this PR, the settings page has gotten a UI revamp. The page now splits each section into their own cards like the other pages. The alert message has been replaced with a snack bar / toast message that displays in the bottom left corner of the screen.
- Alert messages replaced with snack bar / toast messages
- Card components have been reused and wraps around each section
- Alignment has been cleaned up to match the rest of the pages
<details><summary>Click to see screenshots</summary>
<p>
</p>
</details>

Revamp: Settings UI

---

src/data/extension.ts
src/popup/components/PRDisplay/Filters/Filters.tsx
src/popup/components/PRDisplay/index.tsx
src/popup/hooks.tsx

In this PR, the filtering options that are present at the top of the PR Display page are now saved and persisted between uses of the extension / add-on.
- Filter definitions have been moved to `extension.ts`
- Added functions to save and fetch filtering options to and from storage
- onChange handlers are reusing the same single handler, except for the text filter which uses a debounced version
- Data fetching in the base PRDisplay component now has its logic moved into a custom hook

Feature: Filter Options Saved and Persisted

---

src/popup/hooks.tsx

In this PR, the issue where the filters wouldn't load because there was no data when the extension / add-on was first installed has been fixed.
The issue stems from the call to the storage API was successful, but it would return undefined. A check has been introduced that falls back to a default configuration for these filtering options should it return undefined, similar to how we fall back when the call fails and returns an error.
- Added a null coalescing check for when the filters are set on the UI

Bugfix: Filters wouldn't Load on First Use

---

.github/workflows/release.yml

There was an issue where firefox versions wouldn't load and it was due to creating the archives incorrectly. The firefox version was using the chrome version of the build and didn't have the proper manifest file.
- Calling the creation of the archives in the correct folders now

Bugfix: CI/CD Creating Invalid Firefox Releases

---

src/popup/components/PRDisplay/index.tsx
src/popup/components/Settings/AccessTokenSetting.tsx
src/popup/hooks.tsx

In this PR, more clear instructions on how to set your personal access token has been added.
Previously, I have noticed that most people aren't guided to set this token after installing. When first opening the popup, the PR display page will now check if the token has been set in storage, and if it hasn't it will display an informational prompt noting that the user has not done this yet and direct them to the settings page.
- Info messages when personal access token and repos aren't configured
- "Classic" has been added in front of all locations where personal access token is mentioned
- Bold text on settings page to indicate some keywords should the user skim through the instructions
<details><summary>Info prompts</summary>
<p>
</p>
</details> 
<details><summary>Bold texting and classic …

Feature: More Descriptive Personal Access Token Instructions

---

src/popup/components/RepoOptions/components/Add/index.tsx
src/popup/components/RepoOptions/components/Saved/index.tsx

In this PR, the Repos page now has snackbar / toast messages that are displayed when attempting to save or delete a repo. This should help with the feedback when the user interacts with this page.
- Added the snackbar components to the Repos page
Click to see screenshots
<details><summary>Saving</summary>
<p>
</p>
</details> 
<details><summary>Deleting</summary>
<p>
</p>
</details>

Snackbar / Toast messages on Repos page

---

src/data/extension.ts
src/popup/components/PRDisplay/RepoSection/RepoHeader.tsx
src/popup/components/PRDisplay/RepoSection/index.tsx
src/popup/components/PRDisplay/index.tsx
src/popup/components/Settings/CustomUISettings.tsx
src/popup/components/Settings/index.tsx
src/popup/hooks.tsx
src/popup/popup.tsx

In this PR, a new user configuration setting is available on the settings page. The new setting allows the user to pick the behavior they wish to happen when clicking the empty space in between the name of the repo and the dropdown icon for each repository section.
Previously it would just link you to the repo, but some people preferred to be able to expand the section instead. This is the compromise that I came up with that lets the user choose. If there is an error in fetching the settings, it will default to expanding.
- New settings section to set the header click behavior value
- New extension functions to handle getting and setting this header click behavior value
- New hook in React created to fetch this value on the popup
<details><summary>Click to see gifs</summary>
<p>
</p> …

Feature: User configuration for behavior on clicking repo title

---

src/data/extension.ts
src/popup/components/PRDisplay/RepoSection/index.tsx
src/popup/components/PRDisplay/index.tsx
src/popup/components/Settings/AnimatedExpandSettingCard.tsx
src/popup/components/Settings/CustomUISettings.tsx
src/popup/components/Settings/index.tsx
src/popup/hooks.tsx

In this PR, a new setting has been added that the user can configure. Some people may run into the issue where the animation to open a repo section to view the PRs is not smooth or causing the scrollbars to glitch out during the animation. I didn't want to completely get rid of the animations since it looks smooth so I created a setting that is off by default.
If the user wants to allow for the animations, they can enable it in the settings.
- Created a new settings card
- Created a new hook to fetch the settings value
- Created new extension methods to get and save the value to storage
- Setting value is used the RepoSection component to either allow for the Collapse component to be rendered or not allowing for animations
<details open><summary>Click to see GIF</summary>
<p>
</p> …

Feature: Animated Expand Setting

---

src/popup/popup.tsx

When scrolling through one of the pages, if you want to navigate to another page, you will have to scroll back to the top to see the top bar for selecting a new page. This PR, makes the page header stick to the top so that you don't have to scroll back up in order to navigate.
- `popup.jsx` root element now has a `<Box />` component that wraps around the page component
- Scrolling is now only contained to this new `<Box />` component, instead of including the page header components
<details open><summary>Click to see GIF</summary>
<p>
</p>
</details>

Feature: Make Header Stick to the Top

---

src/popup/components/PRDisplay/RepoSection/PullRequest/ReviewIcons.tsx
src/popup/components/PRDisplay/RepoSection/PullRequest/index.tsx

In this PR, the user will now be able to see what pull requests they have recently reviewed. The latest review given by the user is fetched from the GitHub API on each pull request, and based on the type of review they gave, a different icon will be presented.
The currently supported review states that will show icons are for if the user left comments, requested changes, or approved it. It is important to note that the icons don't exactly match up with the icon's in GitHub but are close. To give some clarity, a tooltip will display explaining what the icon means.
- Added a new Icons to the pull request component in the PRDisplay page
<details open><summary>Click to see screenshots</summary>
<p>
</p>
</details>

Feature: Review State on Pull Request Display

---

src/data/index.ts

As part of the shift to GraphQL, one of the things that wasn't properly migrated was the parsing of the Jira tickets, where the ticket wasn't prepended with the configured jira domain. This has been fixed in this PR
- Prepend the detected jira tickets with the Jira domain

Bugfix: Jira Button Now Links Properly

---

src/data/index.ts
src/popup/components/PRDisplay/RepoSection/PullRequest/ReviewIcons.tsx
src/popup/components/PRDisplay/RepoSection/PullRequest/StatusCheckIcons.tsx
src/popup/components/PRDisplay/RepoSection/PullRequest/index.tsx

In this PR, the status check reports have been added to be visible on each pull request.
There are a few things to note:
- The checks may not be completely accurate if the repository is configured with external 3rd party tools for adding checks on a pull request
- The checks icon will show the overall status of success, failed, pending, or if there aren't any configured
- At the moment the performance has taken a hit because the query for the API has become more complicated, this will be addressed before this feature is available for users
- Updated query to fetch status checks information
- Parallelized the query to split up the complexity of the query over multiple calls
- Added new components to render icons next to the author on the pull request and clicking on them will navigate to …

Feature: Status checks for each pull request

---

src/data/index.ts

An earlier PR to fix this issue didn't solve it completely. The domain needs to include `/browse` which was not put in earlier. This PR puts it in to fix that.
- Added `/browse`

Bugfix: Jira Ticket Resolves with `/browse` in the URL

---

src/data/extension.ts
src/popup/components/PRDisplay/RepoSection/PullRequest/index.tsx
src/popup/components/PRDisplay/index.tsx
src/popup/components/Settings/StatusChecksSetting.tsx
src/popup/components/Settings/index.tsx
src/popup/hooks.tsx

In this PR, a new setting has been introduced for the status check feature. By default this setting will be turned off and there is a short description that it may not be completely accurate. More details on why it is labeled as an "experimental" feature is described in #59 
- Added a new hook along with extension methods to save and fetch the configured setting from storage
- Hook is used in the <PRDisplay /> component and passed to each of the <PullRequest /> components
- Updates in <PullRequest />  components to make use of the new setting
<details open><summary>Click to see screenshot</summary>
<p>
</p>
</details>

Feature: Status Check Setting

---

src/popup/components/PRDisplay/RepoSection/RepoHeader.tsx

This PR adds a badge next to each repository’s name, displaying the number of open pull requests for that repo. This provides a quick, at-a-glance indicator of which repos currently have PRs that need attention.
- Introduces a small, rounded badge showing the PR count.
- Leverages existing Material-UI components and styling for a consistent look and feel.
- Helps users quickly identify where to focus their attention without expanding each repo.
Previously, users had to expand each repository section to see if any PRs were open. By displaying the count right in the header, the UI becomes more informative and efficient.

Feature: add badge with pr count for each pr
